import uuid
from app.database import Base, engine, SessionLocal
from app.models import RegulationField, Organization, Product, User, UserRole
from app.auth import get_password_hash

# =============================================================================
# SFDR Fields — fully enriched with legal consequence metadata
# =============================================================================
SFDR_FIELDS = [
    # --- Entity-Level PAI (Principal Adverse Impacts) ---
    {
        "id": "field_pai_ghg_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE1",
        "field_label": "Scope 1 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 1",
        "penalty_tier": "Critical",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "EU Taxonomy", "field_code": "TAX_CLIMATE_MIT", "relationship": "data_dependency"}
        ],
        "guidance": {
            "description": "Scope 1 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ghg_2",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE2",
        "field_label": "Scope 2 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 2",
        "penalty_tier": "Critical",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Scope 2 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ghg_3",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_GHG_SCOPE3",
        "field_label": "Scope 3 GHG Emissions",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 3",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Scope 3 greenhouse gas emissions generated by investee companies.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_carb_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_CARBON_FOOTPRINT",
        "field_label": "Carbon Footprint",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 4",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GHG_SCOPE1", "relationship": "derived_metric"}
        ],
        "guidance": {
            "description": "Carbon footprint of the investment portfolio.",
            "unit": "tCO2e/EURm",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_pai_ff_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_FOSSIL_FUEL",
        "field_label": "Exposure to Fossil Fuel Companies",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 5",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "EU Taxonomy", "field_code": "TAX_FOSSIL_EXCL", "relationship": "exclusion_alignment"}
        ],
        "guidance": {
            "description": "Share of investments in investee companies active in the fossil fuel sector.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_pai_wat_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_WATER_EMISSIONS",
        "field_label": "Emissions to Water",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 8",
        "penalty_tier": "Medium",
        "enforcement_body": "National Competent Authority",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_WATER_USE", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Tonnes of emissions to water generated by investee companies per million EUR invested, expressed as a weighted average.",
            "unit": "tonnes/EURm",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_pai_div_1",
        "framework": "SFDR",
        "disclosure_type": "entity_pai",
        "annex_code": "Annex I, Table 1",
        "field_code": "PAI_BOARD_GENDER_DIVERSITY",
        "field_label": "Board Gender Diversity",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 7(1)(a), RTS Art. 6, Annex I Table 1 Indicator 13",
        "penalty_tier": "Medium",
        "enforcement_body": "National Competent Authority",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GENDER_PAY_GAP", "relationship": "complementary_indicator"},
            {"framework": "CSRD", "field_code": "CSRD_GOVERNANCE_BOARD", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Average ratio of female to male board members in investee companies.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    
    # --- Periodic Report Annexes (Article 8 / Article 9) ---
    {
        "id": "field_per_sustain_target",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_SUSTAIN_INVEST_TARGET",
        "field_label": "Attainment of Sustainable Investment Objective",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [],
        "guidance": {
            "description": "To what extent was the sustainable investment objective attained during the reporting period?",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_top_invest",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_TOP_INVESTMENTS",
        "field_label": "Top Investments",
        "field_kind": "table",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV Section 'What were the top investments?'",
        "penalty_tier": "Medium",
        "enforcement_body": "National Competent Authority",
        "cross_references": [],
        "guidance": {
            "description": "List of top 15 investments of the financial product during the reporting period (Sector, Country, % Assets).",
            "rule_checks": ["table_columns", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_asset_alloc",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_ASSET_ALLOCATION",
        "field_label": "Proportion of Sustainability-related Investments",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV Section 'Asset Allocation'",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [],
        "guidance": {
            "description": "What was the proportion of sustainability-related investments during the reporting period?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_tax_aligned",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_TAXONOMY_ALIGNMENT",
        "field_label": "Taxonomy-aligned Activities",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV; EU Taxonomy Regulation Art. 5-6",
        "penalty_tier": "High",
        "enforcement_body": "National Competent Authority / ESMA",
        "cross_references": [
            {"framework": "EU Taxonomy", "field_code": "TAX_ALIGNMENT_PCT", "relationship": "direct_dependency"}
        ],
        "guidance": {
            "description": "To what extent were the sustainable investments aligned with the EU Taxonomy?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    },
    {
        "id": "field_per_social_obj",
        "framework": "SFDR",
        "disclosure_type": "periodic",
        "annex_code": "Annex IV",
        "field_code": "PERIODIC_SOCIAL_OBJECTIVE",
        "field_label": "Share of Socially Sustainable Investments",
        "field_kind": "numeric",
        "mandatory": False,
        "regulation_version": "2022/1288",
        "legal_basis": "SFDR Art. 11(1), RTS Art. 62, Annex IV (optional social dimension)",
        "penalty_tier": "Low",
        "enforcement_body": "National Competent Authority",
        "cross_references": [
            {"framework": "CSRD", "field_code": "CSRD_GENDER_PAY_GAP", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "What was the share of socially sustainable investments?",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range"]
        }
    }
]

# =============================================================================
# CSRD Cross-Framework Fields — representative set under ESRS standards
# =============================================================================
CSRD_FIELDS = [
    {
        "id": "field_csrd_ghg_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",  # shares disclosure_type for cross-mapping
        "annex_code": "ESRS E1",
        "field_code": "CSRD_GHG_SCOPE1",
        "field_label": "GHG Emissions (ESRS E1 — Scope 1, 2, 3)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E1-6 (Gross GHG emissions)",
        "penalty_tier": "Critical",
        "enforcement_body": "Member State Authority / EFRAG",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE1", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE2", "relationship": "equivalent_disclosure"},
            {"framework": "SFDR", "field_code": "PAI_GHG_SCOPE3", "relationship": "supplementary_data"}
        ],
        "guidance": {
            "description": "Gross Scope 1, 2, and 3 GHG emissions in accordance with ESRS E1-6. Undertakings shall disclose in metric tons of CO2 equivalent.",
            "unit": "tCO2e",
            "rule_checks": ["numeric_only", "must_have_evidence", "positive_value"]
        }
    },
    {
        "id": "field_csrd_water_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS E3",
        "field_code": "CSRD_WATER_USE",
        "field_label": "Water Consumption (ESRS E3)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E3-4 (Water consumption)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_WATER_EMISSIONS", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "Total water consumption in cubic meters, with breakdown by areas of water stress where applicable.",
            "unit": "m³",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_gender_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS S1",
        "field_code": "CSRD_GENDER_PAY_GAP",
        "field_label": "Gender Pay Gap (ESRS S1)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS S1-16 (Remuneration metrics, pay gap)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_BOARD_GENDER_DIVERSITY", "relationship": "complementary_indicator"}
        ],
        "guidance": {
            "description": "The difference between the average gross hourly earnings of male and female employees as a percentage of male gross earnings.",
            "unit": "%",
            "rule_checks": ["numeric_only", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_bio_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS E4",
        "field_code": "CSRD_BIODIVERSITY",
        "field_label": "Biodiversity Impact (ESRS E4)",
        "field_kind": "narrative",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS E4-5 (Impact metrics on biodiversity)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [],
        "guidance": {
            "description": "Disclosure of significant impacts on biodiversity and ecosystems, including land use change and ecosystem degradation.",
            "rule_checks": ["narrative_length", "must_have_evidence"]
        }
    },
    {
        "id": "field_csrd_gov_1",
        "framework": "CSRD",
        "disclosure_type": "entity_pai",
        "annex_code": "ESRS G1",
        "field_code": "CSRD_GOVERNANCE_BOARD",
        "field_label": "Board Composition & Diversity (ESRS G1)",
        "field_kind": "numeric",
        "mandatory": True,
        "regulation_version": "ESRS 2023",
        "legal_basis": "CSRD Art. 19a, ESRS 2 GOV-1 (Board composition)",
        "penalty_tier": "Medium",
        "enforcement_body": "Member State Authority",
        "cross_references": [
            {"framework": "SFDR", "field_code": "PAI_BOARD_GENDER_DIVERSITY", "relationship": "equivalent_disclosure"}
        ],
        "guidance": {
            "description": "Composition of administrative, management and supervisory bodies by gender and other diversity indicators.",
            "unit": "%",
            "rule_checks": ["numeric_only", "percentage_range", "must_have_evidence"]
        }
    }
]

# =============================================================================
# What-If Scenario Templates
# =============================================================================
WHAT_IF_TEMPLATES = [
    {
        "scenario_name": "Non-disclosure of Scope 3 Emissions",
        "scenario_description": "What if we do NOT disclose Scope 3 GHG emissions this reporting period?",
        "parameters": {
            "action": "remove_field",
            "field_code": "PAI_GHG_SCOPE3",
            "rationale": "Data unavailability from portfolio companies"
        }
    },
    {
        "scenario_name": "Board Gender Diversity Below 30%",
        "scenario_description": "What if our Board Gender Diversity drops below 30%?",
        "parameters": {
            "action": "threshold_change",
            "field_code": "PAI_BOARD_GENDER_DIVERSITY",
            "new_value": 28.5,
            "threshold": 30.0,
            "direction": "below"
        }
    },
    {
        "scenario_name": "Fund Reclassification: Article 8 → Article 6",
        "scenario_description": "What if we reclassify this fund from Article 8 to Article 6?",
        "parameters": {
            "action": "reclassify_article",
            "from_article": "Article 8",
            "to_article": "Article 6",
            "rationale": "Simplified disclosure obligations"
        }
    }
]


def seed_database():
    print("Database connection...")
    db = SessionLocal()
    try:
        # 1. Seed users representing distinct governance roles
        users_to_seed = [
            {"id": "system", "username": "System Auto-Agent", "email": "system@sfdr.ai", "role": UserRole.ADMINISTRATOR.value},
            {"id": "user_officer", "username": "officer_alice", "email": "alice@greenfield.com", "role": UserRole.COMPLIANCE_OFFICER.value},
            {"id": "user_reviewer", "username": "reviewer_bob", "email": "bob@greenfield.com", "role": UserRole.REVIEWER.value},
            {"id": "user_admin", "username": "admin_charlie", "email": "admin@greenfield.com", "role": UserRole.ADMINISTRATOR.value}
        ]
        
        for u in users_to_seed:
            existing = db.query(User).filter(
                (User.id == u["id"]) | (User.username == u["username"])
            ).first()
            if not existing:
                new_user = User(
                    id=u["id"],
                    username=u["username"],
                    email=u["email"],
                    hashed_password=get_password_hash("password123"),
                    role=u["role"],
                    active=True
                )
                db.add(new_user)
                print(f"Seeded user: {u['username']} ({u['role']})")
        db.commit()

        # 2. Seed default organization if not exists
        org_id = "default_org"
        org = db.query(Organization).filter(Organization.id == org_id).first()
        if not org:
            org = Organization(id=org_id, name="Greenfield Capital Partners Ltd", type="Asset Manager")
            db.add(org)
            db.commit()
            print(f"Seeded organization: {org.name}")
        else:
            print("Organization already exists.")

        # 3. Seed default products if not exists
        prod_id = "default_prod_8"
        prod = db.query(Product).filter(Product.id == prod_id).first()
        if not prod:
            prod = Product(
                id=prod_id,
                organization_id=org_id,
                name="Greenfield Climate Impact Fund (Art 8)",
                sfdr_article="Article 8",
                strategy="Investments in low-carbon energy transition equities and sustainable real estate.",
                benchmark="MSCI World Climate Change Index"
            )
            db.add(prod)
            
            # Also seed an Article 9 product
            prod9 = Product(
                id="default_prod_9",
                organization_id=org_id,
                name="Greenfield Pure Decarbonization Sovereign Fund (Art 9)",
                sfdr_article="Article 9",
                strategy="100% committed to sustainable investments targeting rapid carbon reduction.",
                benchmark="S&P Global Clean Energy Index"
            )
            db.add(prod9)
            
            db.commit()
            print("Seeded default products (Article 8 and Article 9).")
        else:
            print("Products already exist.")

        # 4. Seed ALL regulation fields (SFDR + CSRD)
        all_fields = SFDR_FIELDS + CSRD_FIELDS
        seeded_count = 0
        for f in all_fields:
            existing = db.query(RegulationField).filter(RegulationField.field_code == f["field_code"]).first()
            if not existing:
                field = RegulationField(
                    id=f["id"],
                    framework=f["framework"],
                    disclosure_type=f["disclosure_type"],
                    annex_code=f["annex_code"],
                    field_code=f["field_code"],
                    field_label=f["field_label"],
                    field_kind=f["field_kind"],
                    mandatory=f["mandatory"],
                    regulation_version=f["regulation_version"],
                    guidance=f["guidance"],
                    # Legal consequence metadata
                    legal_basis=f.get("legal_basis"),
                    penalty_tier=f.get("penalty_tier", "Medium"),
                    enforcement_body=f.get("enforcement_body"),
                    cross_references=f.get("cross_references")
                )
                db.add(field)
                seeded_count += 1
        
        db.commit()
        print(f"Seeded {seeded_count} regulation fields ({len(SFDR_FIELDS)} SFDR + {len(CSRD_FIELDS)} CSRD).")
        
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
